In [2]:
import numpy as np

In [3]:
arr=np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

In [4]:
b=arr[0:2,1:3]
print(b)

[[2 3]
 [6 7]]


In [5]:
print(arr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [6]:
row_r1 = arr[1,:]
row_r2 = arr[1:2,:]
row_r3 = arr[[2],:]
print(row_r1,row_r1.ndim)
print(row_r2, row_r2.ndim)
print(row_r3, row_r3.ndim)

[5 6 7 8] 1
[[5 6 7 8]] 2
[[ 9 10 11 12]] 2


In [7]:
d=np.zeros((3,3))
print(d)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [8]:
e=np.ones((4,3))
print(e)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [9]:
n=np.random.random(3)
print(n)
p=np.random.sample(3)
print(p)

[0.78775657 0.82593851 0.15916045]
[0.59965388 0.33448055 0.26423971]


In [10]:
e=np.random.random((4,3,3))
print(e)
print(f"dimension of matrix is:",e.ndim)

[[[0.554476   0.07339507 0.15531586]
  [0.24514263 0.50272976 0.28020354]
  [0.00913241 0.94349972 0.64956165]]

 [[0.82605127 0.71502859 0.75770072]
  [0.52119715 0.27392375 0.46235294]
  [0.4524919  0.11707116 0.96224146]]

 [[0.172815   0.13556877 0.62256034]
  [0.9118526  0.14412575 0.04154198]
  [0.43247549 0.70519075 0.29492128]]

 [[0.15685208 0.24592019 0.21296371]
  [0.57191536 0.55727228 0.71854043]
  [0.28001762 0.48877041 0.73220802]]]
dimension of matrix is: 3


In [11]:
c=np.full((2,2),2)
print(c)

[[2 2]
 [2 2]]


In [12]:
d=np.eye(2)
print(d)
print(d.dtype)

[[1. 0.]
 [0. 1.]]
float64


Stack

In [13]:
a=np.array([1,2,3])
b=np.array([4,5,6])
np.vstack((a,b))    #vertica stack


array([[1, 2, 3],
       [4, 5, 6]])

In [14]:
a=np.array(([1],[2],[3]))
print(a)
b=np.array(([2],[4],[6]))
print(b)
np.hstack((a,b))

[[1]
 [2]
 [3]]
[[2]
 [4]
 [6]]


array([[1, 2],
       [2, 4],
       [3, 6]])

Datatypes

In [15]:
x=np.array([1.0,2])
print(x.dtype)

float64


Array Math

In [16]:
a=np.random.random(1000000000)
a

array([0.49686942, 0.81605693, 0.22296015, ..., 0.97580344, 0.35072159,
       0.15897864])

In [23]:
%%time
z=np.sum(a)

CPU times: total: 7.12 s
Wall time: 11.5 s


In [ ]:
x=np.array(([1,2],[3,4]))
y=np.array(([2,2],[4,4]))
print(f"addition is:" ,np.add(x,y))
print(f"subtraction is:",np.subtract(x,y))
print(f"multiplication is:",np.subtract(x,y))
print(f"division is:",np.subtract(x,y))
#sqrt for square root

addition is: [[3 4]
 [7 8]]
subtraction is: [[-1  0]
 [-1  0]]


Day 2 ***


Dot Product

In [18]:
x=np.array(([1,2],[3,4]))
y=np.array(([2,2],[4,4]))

u=np.array(([1,2],[3,4]))
i=np.array(([2,2],[4,4]))

#inner dot product
print(u.dot(i))
print(np.dot(u,i))

[[10 10]
 [22 22]]
[[10 10]
 [22 22]]


In [22]:
v=np.array(([1,2,3],[4,5,6],[7,8,9]))
u=np.array(([9,8,7],[6,5,4],[3,2,1]))
print(v.dot(u))
print(np.dot(v,u))
print(v @ v)        #also a dot product

[[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]
[[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]
[[ 30  36  42]
 [ 66  81  96]
 [102 126 150]]
