In [2]:
#This module gets the data from the user and then Logistic Regression evaluates based on the data 
#And, predicts how much a student might score in the exam

import numpy as np
import pandas as pd


In [3]:
data=pd.read_csv('StudentPerformanceFactors.csv')
df1=data

In [4]:
data.head()
data.isnull().sum()

Hours_Studied                  0
Attendance                     0
Parental_Involvement           0
Access_to_Resources            0
Extracurricular_Activities     0
Sleep_Hours                    0
Previous_Scores                0
Motivation_Level               0
Internet_Access                0
Tutoring_Sessions              0
Family_Income                  0
Teacher_Quality               78
School_Type                    0
Peer_Influence                 0
Physical_Activity              0
Learning_Disabilities          0
Parental_Education_Level      90
Distance_from_Home            67
Gender                         0
Exam_Score                     0
dtype: int64

In [5]:
df1.drop(columns=['Distance_from_Home','Parental_Education_Level','School_Type'], inplace=True)


In [6]:
df1
df1.dropna(inplace=True)

In [7]:
a=df1.columns
a

Index(['Hours_Studied', 'Attendance', 'Parental_Involvement',
       'Access_to_Resources', 'Extracurricular_Activities', 'Sleep_Hours',
       'Previous_Scores', 'Motivation_Level', 'Internet_Access',
       'Tutoring_Sessions', 'Family_Income', 'Teacher_Quality',
       'Peer_Influence', 'Physical_Activity', 'Learning_Disabilities',
       'Gender', 'Exam_Score'],
      dtype='object')

In [8]:
#string value error so lets assign numeric values
ordinal_mapping = {
    'Low': 0,   #Parental_Involvement, Teacher_Quality, Family_Income, Access_to_Resources, Motivation_Level
    'Medium': 1,
    'High': 2,
    'Yes': 1,   #Extracurricular_Activities, Internet_Access, Learning_Disabilities
    'No': 0,
    'Positive': 1,  #Peer_Influence
    'Negative': 0,
    'Neutral': 2,
    'Male': 1, #Gender
    'Female': 0
}
df1['Parental_Involvement'] = df1['Parental_Involvement'].map(ordinal_mapping)
df1['Teacher_Quality'] = df1['Teacher_Quality'].map(ordinal_mapping)    
df1['Family_Income'] = df1['Family_Income'].map(ordinal_mapping)
df1['Access_to_Resources'] = df1['Access_to_Resources'].map(ordinal_mapping)
df1['Motivation_Level'] = df1['Motivation_Level'].map(ordinal_mapping)
df1['Extracurricular_Activities'] = df1['Extracurricular_Activities'].map(ordinal_mapping)
df1['Internet_Access'] = df1['Internet_Access'].map(ordinal_mapping)
df1['Learning_Disabilities'] = df1['Learning_Disabilities'].map(ordinal_mapping)
df1['Peer_Influence'] = df1['Peer_Influence'].map(ordinal_mapping)
df1['Gender'] = df1['Gender'].map(ordinal_mapping)

In [9]:
features = a

In [10]:
X= data[features]
y= data['Exam_Score']

In [11]:
# Time to train
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [12]:
# standardize the data
from sklearn.preprocessing import StandardScaler   
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [13]:
from sklearn.linear_model import LogisticRegression
#Creating and training Logistic regression model 
model = LogisticRegression()
model.fit(X_train, y_train)

c:\Users\RICKY\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [14]:
#prediction
y_pred = model.predict(X_test)

In [22]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
#prediction and evaulation
y_pred = model.predict(X_test)
print("Accuracy:", accuracy_score(y_test, y_pred))
print("Consufion matrix:\n", confusion_matrix(y_test, y_pred))
print("Classification report:\n", classification_report(y_test, y_pred))

Accuracy: 0.6431852986217458
Consufion matrix:
 [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 2 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 1 0]]
Classification report:
               precision    recall  f1-score   support

          55       0.00      0.00      0.00         1
          57       0.00      0.00      0.00         1
          58       0.67      0.33      0.44         6
          59       0.17      0.33      0.22         3
          60       0.40      0.13      0.20        15
          61       0.56      0.42      0.48        43
          62       0.42      0.40      0.41        50
          63       0.58      0.65      0.61        62
          64       0.64      0.65      0.64        85
          65       0.75      0.84      0.79       129
          66       0.81      0.84      0.82       152
          67       0.77      0.70      0.73       141
          68       0.69      0.87      0.77       165
          69       0.75      0.61      0.68       1

c:\Users\RICKY\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\metrics\_classification.py:1517: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\RICKY\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\metrics\_classification.py:1517: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\RICKY\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\metrics\_classification.py:1517: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, 

In [16]:
import joblib

joblib.dump(model, 'logistic_regression_model.joblib')
joblib.dump(scaler, 'Student_dataset.joblib')

['Student_dataset.joblib']

In [17]:
#loaded model from joblib and predict using any sample
loaded_model = joblib.load('logistic_regression_model.joblib')
loaded_scaler = joblib.load('Student_dataset.joblib')


In [18]:
df1.columns

Index(['Hours_Studied', 'Attendance', 'Parental_Involvement',
       'Access_to_Resources', 'Extracurricular_Activities', 'Sleep_Hours',
       'Previous_Scores', 'Motivation_Level', 'Internet_Access',
       'Tutoring_Sessions', 'Family_Income', 'Teacher_Quality',
       'Peer_Influence', 'Physical_Activity', 'Learning_Disabilities',
       'Gender', 'Exam_Score'],
      dtype='object')

In [19]:
#random test
sample_data = np.array([[20, 80, 2, 2, 1, 7, 70, 1, 1, 3, 2, 1, 1, 3, 0, 1,1 ]]) 
# hours_studied, Attendance, parental_involvement, Access_to_Resource, extracurricular_activities, Sleep_hours, Previous_score,
# motivation_level, Internet_Access, Tutoring_Sessions, teacher_quality, family_income, peer_influence, physical_activity,learning_disabilities, 
# gender

In [20]:
prediction = loaded_model.predict(loaded_scaler.transform(sample_data))

c:\Users\RICKY\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(


In [21]:
prediction[0]

61