In [2]:
import numpy as np

In [3]:
data = np.array ([1,2,3,4,5,6,7,8])
data.reshape(2,4)
w=np.array([[1],[2],[3],[4]])
print(w)
w.shape
y=w.reshape(-1)
print(y)
y.shape

[[1]
 [2]
 [3]
 [4]]
[1 2 3 4]


(4,)

In [4]:
w=np.array([[1],[2],[3]])

z= w.squeeze()
print(z)
z.shape

[1 2 3]


(3,)

In [5]:
#creating array with shape
arr= np.array([[1,2,3]])
print(arr.shape)

squeeze_arr= np.squeeze(arr)
print(squeeze_arr.shape)
print(squeeze_arr)


(1, 3)
(3,)
[1 2 3]


Squeeze array in 3D

In [6]:
arr= np.array([[[1],[2]]])
print(arr.shape)

#squeeze to remove the single dimensional axes
squeezed_arr= np.squeeze(arr)
print(squeezed_arr.shape)
print(squeezed_arr)


(1, 2, 1)
(2,)
[1 2]


To go from 1D to 2D array, we can just add in another dimension of size 1

In [ ]:
import numpy as np
y= np.array([1,2])
print(y.ndim)
y=y.reshape((-1,1,1))
print(y.ndim)

1
3


In [3]:
m=np.squeeze(y)
m

array([1, 2])

Broadcast

In [ ]:
import numpy as np

#Rule no 1: The number of dimensions must be the same

a= np.array([1,2,3])
print(a)

b=np.array([[4],[5],[6]])
print(b)

c=a+b
print(c)

[1 2 3]
[[4]
 [5]
 [6]]
[[5 6 7]
 [6 7 8]
 [7 8 9]]


In [4]:
#Rule no 2: No dimension matches. 
a=np.array([[1],[2],[3]])
print(a)

b=np.array([[4,5],[6,7],[8,9]])
print(b)

c=a+b
print(c)

[[1]
 [2]
 [3]]
[[4 5]
 [6 7]
 [8 9]]
[[ 5  6]
 [ 8  9]
 [11 12]]


In [9]:
#Rule no 3: If in any dimension the sizes disagree and neither is equal to 1, an error is raised.
mat1=np.array([[1,2,3,4,5],[1,2,3,4,5],[1,2,3,4,5],[1,2,3,4,5]])
print(mat1)

mat2=np.array([[2,2],[1,1]])
print(mat2)

mat3=mat1+mat2
print(mat3)

[[1 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]]
[[2 2]
 [1 1]]


ValueError: operands could not be broadcast together with shapes (4,5) (2,2) 

More linear Algebra with numpy

In [6]:
import numpy as np
A=np.array([[1,2],[3,4]])

# Determinant of a matrix
det_A = np.linalg.det(A)
print("Determinant of A is:", det_A)

Determinant of A is: -2.0000000000000004


Solving Linear Equations

In [ ]:
#Example of system linear equations
#3x + y -2z= 9
#2x - y + z =3
#x + 2y + 3z = 12

A = np.array([[3, 1, -2], [2, -1, 1], [1, 2, 3]])
b= np.array([9, 3, 12])

Solutions = np.linalg.solve(A, b)
print(f"Solution of the given 3D linear equations are:\n", Solutions)

Solution of the given 3D linear equations are:
 [2.6 3.2 1. ]


Random number with numpy

In [13]:
#generate a single random number between 0 and 1
random_number= np.random.rand()
print(f"\nsingle random number between 0 and 1:\n" ,random_number)

#generate a 1D array of 5 random numbers 
random_array_1D= np.random.rand(5)
print(f"\n1D array of 5 random numbers:\n ", random_array_1D)

#generate a 2D array of random numbers(3*3)
random_array_2D= np.random.rand(3,3)
print(f"\n2D array of random numbers(3*3):\n", random_array_2D)


single random number between 0 and 1:
 0.38159544563754666

1D array of 5 random numbers:
  [0.28206056 0.18938748 0.52486771 0.29686993 0.02695716]

2D array of random numbers(3*3):
 [[0.29309164 0.68947274 0.88648137]
 [0.58052706 0.18908953 0.20521459]
 [0.77346977 0.84435627 0.17960154]]


Random Integers

In [14]:
#generate a single integer between 0 and 10
rand_int = np.random.randint(0,10)
print(rand_int)

#generate a 1D array of 5 random integers between 0 and 10

random_int_array= np.random.randint(0,10,size=5)
print(random_int_array)

#generate a 2D array of random integers between 0 and 10
rand_int_array_2d= np.random.randint(0,10,size=(3,2))
print(rand_int_array_2d)


5
[0 0 1 9 2]
[[1 0]
 [4 7]
 [9 6]]


In [15]:
#Randomly choose 3 elements from the list [1,2,3,4,5]
random_sample=np.random.choice([1,2,3,4,5],size=3)
print(random_sample)

#sample with replacement(the same element can be chosen more than once)
random_sample_with_replacement= np.random.choice([1,2,3,4,5],size=3,replace=True)
print(random_sample_with_replacement)

[5 3 1]
[2 4 2]


Random numbers with specified seeds (Reproducibility)

In [19]:
#set the seed for reproducibility
np.random.seed(42)

#generate random numbers
random_numbers = np.random.rand(3)
print(random_numbers)

#set the seed again and generate same numbers 
np.random.seed(42)
random_numbers_again=np.random.rand(3)
print(random_numbers_again)

[0.37454012 0.95071431 0.73199394]
[0.37454012 0.95071431 0.73199394]
