In [1]:
import numpy as np

In [9]:
preds=np.array([0.2,0.5,0.92,0.9,0.1])
predicted_class_index = np.argmax(preds)
predicted_class_index

to_predict_class=["apple","banana","ball","mango","orange"]
possible_class_indexes=np.where(preds>0.85)[0]

for possible_class_index in possible_class_indexes:
    print(to_predict_class[possible_class_index])

ball
mango


-argmax (get index of maximum element in array)

-argmin (get index of minimum element in array)

-argsort (get sorted list of indices, by element value in ascending order)

-where (get indices of element that meet same condition)

In [17]:
a=np.array([1,8,9,-3,2,4,7,9])

#get the index of the amximum element in a
print(f"The maximum value in the array is:",np.argmax(a))
print(f"The minimum value in the array is:",np.argmin(a))
print(f"The sorted value in ascending order is:",np.argsort(a)) #ascending order
#for descending order
#[::-1] is the slicing index that returns the reversed list
print(f"The sorted value in descending order is:",np.argsort(a)[::-1]) 

#get the indices of the element that meets certain conditions
#this returns a tuple, the list of the indices is the first entry
#so we use [0] to get it 
print(f"Greater than five only using where condition:", np.where(a>5)[0])


The maximum value in the array is: 2
The minimum value in the array is: 3
The sorted value in ascending order is: [3 0 4 5 6 1 2 7]
The sorted value in descending order is: [7 2 1 6 5 4 0 3]
Greater than five only using where condition: [1 2 6 7]


Some more simple methods: max, min, sum

In [19]:
x=np.array([[1,2],[3,4],[5,6]])

print(f"The maximum of the element:",np.max(x))
print(f"The minimum of the element:",np.min(x))
print(f"The sum of the element:",np.sum(x))



The maximum of the element: 6
The minimum of the element: 1
The sum of the element: 21


In [20]:
x=np.array([[1,2,8],[5,3,1],[4,6,5]])
print(x)

print(f"The maximum of each column:",np.max(x, axis=0))
print(f"The maximum of each row:",np.max(x, axis=1))


[[1 2 8]
 [5 3 1]
 [4 6 5]]
The maximum of each column: [5 6 8]
The maximum of each row: [8 5 6]


Transpose and reshape


In [24]:
arary=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arary)
print(f"The transpose of the matrix is:\n", arary.T)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
The transpose of the matrix is:
 [[1 4 7]
 [2 5 8]
 [3 6 9]]
